[committee]
members = [
    "celinval",
    "rahulku",
    "pnkfelix",
    "adpaco-aws",
    "feliperodri",
    "remi-delmas-3000",
    "tautschnig",
    "patricklam",
    "ranjitjhala",
    "carolynzech",
    "HuStmpHrrr",
    "jswrenn",
    "havelund",
    "jorajeev",
    "rajath-mk",
    "thanhnguyen-aws",
    "btj",
    "rafaelsamenezes"
]
