[package]
name = "assert-instr"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
assert-instr-macro = { path = "assert-instr-macro" }
backtrace = "0.3"
cc = "1.0"
lazy_static = "0.2"
rustc-demangle = "0.1"
