[package]
name = "assert-instr-macro"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "0.1", features = ["unstable"] }
quote = { git = 'https://github.com/dtolnay/quote' }
syn = { git = 'https://github.com/dtolnay/syn', features = ["full"] }
synom = { git = 'https://github.com/dtolnay/syn' }
