[package]
name = "unsafe-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
prettyplease = "0.2.32"
syn = {version = "2.0.101", features = ["full", "extra-traits", "visit"]}
csv = "1.1"
serde = { version = "1.0.55", features = ["derive"] }
regex = "1.11.2"
itertools = "0.14.0"
