[package]
name = "stdsimd"
version = "0.0.2"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Experiments for adding SIMD support to Rust's standard library."
documentation = "https://docs.rs/stdsimd"
homepage = "https://github.com/BurntSushi/stdsimd"
repository = "https://github.com/BurntSushi/stdsimd"
readme = "README.md"
keywords = ["std", "simd", "intrinsics", "sse", "avx"]
license = "MIT"

[profile.release]
debug = true
opt-level = 3

[profile.bench]
debug = true
opt-level = 3

[dev-dependencies]
assert-instr = { path = "assert-instr" }