name: KMIR

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches: [ main ]
  push:
    paths:
      - 'library/**'
      - '.github/workflows/kmir.yml'
      - 'kmir-proofs/**'

defaults:
  run:
    shell: bash

jobs:
  run-kmir-proofs:
    name: Run supplied KMIR proofs
    runs-on: ubuntu-latest
    env:
      container_name: "kmir-${{ github.run_id }}"
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Tool Container
        run: |
          docker run --detach --rm -t \
            --name ${{ env.container_name }} \
            -v $PWD:/workspace -w /workspace \
            -u $(id -u):$(id -g) \
            runtimeverificationinc/kmir:ubuntu-jammy-0.3.112_7.1.229-daf5158 /bin/bash

      - name: Run KMIR Verification for all proofs provided
        run: |
          for k_file in kmir-proofs/*/*-spec.k; do
            echo "Running ${k_file}"
            docker exec ${{ env.container_name }} kmir prove run ${k_file} --proof-dir $(dirname ${k_file})/proofs
          done

      - name: Stop Tool Container
        if: always()
        run: docker stop ${{ env.container_name }}
